version: "2.2"
services:
    app-data:
        build: .
        volumes:
          - app-data:/pp-app
        entrypoint:
          - /bin/sh
          - -c
          - |
            cp -r /planningpoker/* /pp-app/ && touch /pp-app/deployed.txt
    app:
        container_name: planningpoker-app
        image: node:17.2.0-slim
        ports:
            - "4200:4200"
        volumes:
            - app-data:/app/PlanningPoker
            - ./data/:/app/PlanningPoker/data
        entrypoint:
            - /bin/sh
            - -c
            - |
              cd /app/PlanningPoker && until [ -e deployed.txt ]; do echo "wait"; sleep 1; done && rm deployed.txt && echo "starting" && npm start
        networks:
            - default
    backend-data:
        build: api/.
        volumes:
          - python-script:/python-data
          - pip-packages:/pip-packages-data
        entrypoint:
          - /bin/sh
          - -c
          - |
            cp -r /pip-packages/* /pip-packages-data/ && cp -r /python/* /python-data/ && touch /python-data/deployed.txt
    backend:
        container_name: planningpoker-backend
        image: python:3-slim
        volumes:
            - python-script:/usr/src/app/script
            - pip-packages:/usr/local/lib/python3.10/site-packages
            - ./data/:/usr/src/app/data
            - ./src/assets/poker-config.json:/usr/src/app/src/assets/poker-config.json
        entrypoint:
            - /bin/sh
            - -c
            - |
              cd /usr/src/app/ && until [ -e /usr/src/app/script/deployed.txt ]; do echo "wait"; sleep 1; done && rm script/deployed.txt && mv script/api.py . && echo "starting" && python api.py
        networks:
            - default
volumes:
  python-script:
    driver_opts:
      type: tmpfs
      device: tmpfs
  pip-packages:
    driver_opts:
      type: tmpfs
      device: tmpfs
  app-data:
    driver_opts:
      type: tmpfs
      device: tmpfs

